### ISSUE TITLE
Tag Cargo Releases

### ISSUE THREAD

**Issue by notpeter** [stainless-steel/random#3]
I went through the historical cargo releases to match the commits from this repo:

version | commit
------- | ------------------
v0.13.2 | bb1d7dde30ead9e39a23a360ddcea19769a8524b
v0.13.1 | 9318db73386b43843a9c881ffe3c765592354ca7
v0.13.0 | 6b60776ab80a9501cc73d8e3a475beb7fa621c01
v0.12.2 | e5301b364865d851f794bec3c4852dc3e560b1fe
v0.12.1 | a5a604c2500aa6824eeba592546b017f33e76e1b
v0.11.0 | 4068b624f7d987c229ce3b3d39fe06bb1943ec14
v0.10.1 | 7526b1eff7b9d931b8c94f0d9716c78239f0d14a
v0.10.0 | c29e667ef966ce60024ebf436266ebacff2e1201
v0.9.2 | e4d874626874e563fc07449256c6d7d167c6229a
v0.9.1 | 9bbf70d3f48947e504694e1d0ae8f376b132e994
v0.9.0 | d252a69d2ef698f177fdbad61b5a17a7b2d125d6
v0.8.0 | 41df3b63b47c43507fe2d795b05492720f119b39
v0.7.0 | 62cbac4d3957b5250eada7a585a553a402898686
v0.6.2 | eddd11acac8147a5b23912ee254aef112c0ade19
v0.6.1 | 28beb263d29891d21cd84f474614c6d4e2a0cd83
v0.6.0 | 920d4a06124bab8ea32acb6096a01781f66f09c5
v0.5.0 | d4293938664c15d0fc6cf2df9392b0d3ea86b14d
v0.4.0 | d124e1e5135ee96c7e22e107d3185827dc57235c
v0.3.0 | 282630734ca95d1bcaf112e7cb38923b5d5d5039
v0.2.0 | 7b6aa72a2526eb55f1b9ada8156af34bd145959a
v0.1.0 | a77dbb82dda6bf03a4078a2b70cf2b8336b6eae9
v0.0.1 | 81dcf543c5c82c8354def49ed0524fc904dac4bc 

Could you tag those releases? 

```
git tag v0.13.2 bb1d7dde30ead9e39a23a360ddcea19769a8524b
git tag v0.13.1 9318db73386b43843a9c881ffe3c765592354ca7
git tag v0.13.0 6b60776ab80a9501cc73d8e3a475beb7fa621c01
git tag v0.12.2 e5301b364865d851f794bec3c4852dc3e560b1fe
git tag v0.12.1 a5a604c2500aa6824eeba592546b017f33e76e1b
git tag v0.11.0 4068b624f7d987c229ce3b3d39fe06bb1943ec14
git tag v0.10.1 7526b1eff7b9d931b8c94f0d9716c78239f0d14a
git tag v0.10.0 c29e667ef966ce60024ebf436266ebacff2e1201
git tag v0.9.2 e4d874626874e563fc07449256c6d7d167c6229a
git tag v0.9.1 9bbf70d3f48947e504694e1d0ae8f376b132e994
git tag v0.9.0 d252a69d2ef698f177fdbad61b5a17a7b2d125d6
git tag v0.8.0 41df3b63b47c43507fe2d795b05492720f119b39
git tag v0.7.0 62cbac4d3957b5250eada7a585a553a402898686
git tag v0.6.2 eddd11acac8147a5b23912ee254aef112c0ade19
git tag v0.6.1 28beb263d29891d21cd84f474614c6d4e2a0cd83
git tag v0.6.0 920d4a06124bab8ea32acb6096a01781f66f09c5
git tag v0.5.0 d4293938664c15d0fc6cf2df9392b0d3ea86b14d
git tag v0.4.0 d124e1e5135ee96c7e22e107d3185827dc57235c
git tag v0.3.0 282630734ca95d1bcaf112e7cb38923b5d5d5039
git tag v0.2.0 7b6aa72a2526eb55f1b9ada8156af34bd145959a
git tag v0.1.0 a77dbb82dda6bf03a4078a2b70cf2b8336b6eae9
git tag v0.0.1 81dcf543c5c82c8354def49ed0524fc904dac4bc

git push --tags
```

Thanks, -Peter

**Comment by IvanUkhov** [comment]
Hello, can you please motivate this? Why is it needed?

**Comment by notpeter** [comment]
I have software which has random as a dependency. I wanted to see what had changed between the old version and current version.  With tags it becomes trivially easy to use compare/tag1..tag2 on github. Without tags I'm left exploring all commits manually to cross-reference. So I took an extra 10mins to match all the crate releases versions to git commit sha1s.

In the end it's just bonus metadata.
![metaData: a love note to the future](https://user-images.githubusercontent.com/145113/203060466-41636f3a-864e-4381-b5a9-75250b82af2b.jpeg)

**Comment by IvanUkhov** [comment]
Yes, this is very much reasonable. I pushed it. It is a one-off, but it would good to adopt this practice in all crates and somehow automate it. Thank you for the note!

**Comment by notpeter** [comment]
Thanks @IvanUkhov.  Yeah, at some point 3-4 years ago it got somewhat easier to backfill cargo releases to commits with the introduction of [.cargo_vcs_info.json](https://docs.rs/crate/random/0.13.2/source/.cargo_vcs_info.json) which docs.rs makes easily accessible.  I haven't found a reliable way to validate commit ids prior those (other than manually) and of course maintainers can also upload with `--allow-dirty` too.

Probably wouldn't be too tough to build a bot to iterate through a project and see if it could match up crate versions with commits based on content.  Anyways, thanks for tagging.
