### ISSUE TITLE
Is it possible to eliminate usage of any float type?

### ISSUE THREAD

**Issue by staystealth** [stainless-steel/random#4]
Hi, is it possible to modify "random" crate, to avoid usage of float numbers at all? If it's possible could you drop some details which part of your program use it and for what reason?

**Comment by IvanUkhov** [comment]
Hi, I am not sure I understand your motivation. Could you please elaborate?

**Comment by staystealth** [comment]
Sure, thanks for reply. I'm using random::default to generate Xorshift128Plus to get random generated values in my program,  it works really smooth, but when i'm using 'cosmwasm-check' (which basically checks my wasm file if it is secure to be uploaded to the blockchain and used as a smart contract) it throws an err `WebAssembly translation error: Error in middleware Gatekeeper: Float operator detected: F64Load` and here comes my question if random::default uses float values at some point to generate Xorshift128Plus, and if, is it possible to modify the source code to be able to avoid using float values durning generation at all?

**Comment by IvanUkhov** [comment]
The crate provides two functions: one for generating integers and one for generating floats:

https://github.com/stainless-steel/random/blob/main/src/source.rs#L5-L12

Floats are not necessary for generating pseudo-random integers but, of course, required for floats.
